### ISSUE TITLE
Question - Intl Dependency

### ISSUE THREAD

**Issue by lwelti** [formatjs/intl-relativeformat#45]
hi, you mention that you have an Intl dependency, but where is that and why ? if you already have the metadata in your library.

thanks in advance.

**Comment by caridy** [comment]
Lucas, the dependecy is just to make sure that the global `Intl` object exists, whether that's native or a polyfill, doesn't really matter, and this pkg will not really import that dependency, it will just do a simple check to make sure that the runtime works fine with `Intl`.

**Comment by lwelti** [comment]
because i could use it without having that dependency, or not?

**Comment by caridy** [comment]
that is correct, if your runtime already have `Intl`, you can use intl-relativeformat directly.

**Comment by gajus** [comment]
>> because i could use it without having that dependency, or not?
> that is correct, if your runtime already have Intl, you can use intl-relativeformat directly.

You don't need `Intl` global for node.js (as of v4).

In browser environment, you need to polyfill `Intl` if you want to support Safari 9 (which is the current version). Safari 10 does support `Intl`.

http://caniuse.com/#search=Intl

This issue can be closed.

**Comment by longlho** [comment]
Intl is available in all browsers IE11+ now
