### ISSUE TITLE
Align with ECMA402 spec proposal

### ISSUE THREAD

**Issue by zbraniecki** [formatjs/intl-relativeformat#56]
Great to see this polyfill!

We reached stage 3 with the spec proposal - https://github.com/tc39/proposal-intl-relative-time - and are looking for implementers feedback.

I just landed a native implementation in SpiderMonkey, but that's going to be behind the flag for a while, and it would be good to have more more implementations provide feedback on the current language of the spec.

Also, it would be very helpful to get people working on this polyfill to contribute to the open issues - https://github.com/tc39/proposal-intl-relative-time/issues

Thanks!

**Comment by longlho** [comment]
Released in https://www.npmjs.com/package/@formatjs/intl-relativetimeformat (tested w/ test262)
